return {
  { "fei6409/log-highlight.nvim", event = "BufRead *.log", opts = {} },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "lua",
        "go",
        "javascript",
        "jsdoc",
        "json",
        "caddy",
        "cmake",
        "css",
        "devicetree",
        "gitcommit",
        "gitignore",
        "glsl",
        "go",
        "http",
        "nix",
        "php",
        "rust",
        "scss",
        "sql",
        "svelte",
        "toml",
        "typescript",
        "vue",
        "wgsl",
      },
      highlight = { enable = true },
      autotag = { enable = true },
      indent = { enable = true },
      auto_install = true,
    },
  },
}
