-- Calamity colorscheme — matches Ghostty Calamity theme
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "calamity"
vim.o.background = "dark"

local c = require("calamity")

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base (transparent background — terminal bg shows through)
hi("Normal",          { fg = c.fg })
hi("NormalNC",        { fg = c.fg })
hi("NormalFloat",     { fg = c.fg,      bg = c.bg_float })
hi("FloatBorder",     { fg = c.comment, bg = c.bg_float })
hi("FloatTitle",      { fg = c.cyan,    bg = c.bg_float, bold = true })
hi("SignColumn",      { fg = c.comment })
hi("ColorColumn",     {                 bg = c.bg_dark })
hi("CursorLine",      {                 bg = c.bg_hl })
hi("CursorLineNr",    { fg = c.yellow,  bold = true })
hi("CursorColumn",    {                 bg = c.bg_hl })
hi("LineNr",          { fg = c.comment })
hi("EndOfBuffer",     { fg = c.bg_dark })
hi("FoldColumn",      { fg = c.comment })
hi("Folded",          { fg = c.comment, bg = c.bg_dark })
hi("VertSplit",       { fg = c.bg_hl })
hi("WinSeparator",    { fg = c.bg_hl })

-- Selection / Search
hi("Visual",          {                 bg = c.bg_visual })
hi("VisualNOS",       {                 bg = c.bg_visual })
hi("Search",          { fg = c.bg,      bg = c.yellow })
hi("IncSearch",       { fg = c.bg,      bg = c.magenta })
hi("CurSearch",       { fg = c.bg,      bg = c.magenta })
hi("Substitute",      { fg = c.bg,      bg = c.red })

-- Syntax
hi("Comment",         { fg = c.comment, italic = true })
hi("Constant",        { fg = c.yellow })
hi("String",          { fg = c.green })
hi("Character",       { fg = c.green })
hi("Number",          { fg = c.orange })
hi("Boolean",         { fg = c.magenta })
hi("Float",           { fg = c.orange })
hi("Identifier",      { fg = c.fg })
hi("Function",        { fg = c.cyan })
hi("Statement",       { fg = c.magenta })
hi("Conditional",     { fg = c.magenta })
hi("Repeat",          { fg = c.magenta })
hi("Label",           { fg = c.magenta })
hi("Operator",        { fg = c.cyan })
hi("Keyword",         { fg = c.magenta, italic = true })
hi("Exception",       { fg = c.red })
hi("PreProc",         { fg = c.yellow })
hi("Include",         { fg = c.blue })
hi("Define",          { fg = c.magenta })
hi("Macro",           { fg = c.yellow })
hi("PreCondit",       { fg = c.yellow })
hi("Type",            { fg = c.yellow })
hi("StorageClass",    { fg = c.magenta })
hi("Structure",       { fg = c.yellow })
hi("Typedef",         { fg = c.yellow })
hi("Special",         { fg = c.cyan })
hi("SpecialChar",     { fg = c.cyan })
hi("Tag",             { fg = c.cyan })
hi("Delimiter",       { fg = c.fg_dim })
hi("SpecialComment",  { fg = c.comment, italic = true })
hi("Debug",           { fg = c.red })
hi("Underlined",      { underline = true })
hi("Error",           { fg = c.red })
hi("Todo",            { fg = c.bg, bg = c.yellow, bold = true })

-- UI
hi("StatusLine",      { fg = c.fg,      bg = c.bg_float })
hi("StatusLineNC",    { fg = c.comment, bg = c.bg_float })
hi("TabLine",         { fg = c.comment, bg = c.bg_dark })
hi("TabLineFill",     {                 bg = c.bg_dark })
hi("TabLineSel",      { fg = c.fg,      bg = c.bg, bold = true })
hi("WildMenu",        { fg = c.bg,      bg = c.cyan })
hi("Pmenu",           { fg = c.fg,      bg = c.bg_float })
hi("PmenuSel",        { fg = c.fg,      bg = c.bg_visual, bold = true })
hi("PmenuSbar",       {                 bg = c.bg_dark })
hi("PmenuThumb",      {                 bg = c.comment })
hi("MatchParen",      { fg = c.cyan,    bg = c.bg_hl, bold = true })
-- Plugins also use NonText/SpecialKey for secondary text, not just whitespace.
hi("NonText",         { fg = c.fg_dim })
hi("SpecialKey",      { fg = c.fg_dim })
hi("Whitespace",      { fg = c.bg_hl })
hi("Title",           { fg = c.cyan, bold = true })
hi("Directory",       { fg = c.blue })
hi("QuickFixLine",    {                 bg = c.bg_hl })
hi("Question",        { fg = c.green })
hi("MoreMsg",         { fg = c.green })
hi("ModeMsg",         { fg = c.yellow })
hi("WarningMsg",      { fg = c.yellow })
hi("ErrorMsg",        { fg = c.red })

-- Snacks picker: keep paths readable without competing with filenames.
hi("SnacksPickerDir",         { fg = c.fg_dim })
hi("SnacksPickerPathHidden",  { fg = c.fg_dim })
hi("SnacksPickerPathIgnored", { fg = c.fg_dim })

-- Diagnostics
hi("DiagnosticError",            { fg = c.red })
hi("DiagnosticWarn",             { fg = c.yellow })
hi("DiagnosticInfo",             { fg = c.blue })
hi("DiagnosticHint",             { fg = c.cyan })
hi("DiagnosticOk",               { fg = c.green })
hi("DiagnosticUnderlineError",   { undercurl = true, sp = c.red })
hi("DiagnosticUnderlineWarn",    { undercurl = true, sp = c.yellow })
hi("DiagnosticUnderlineInfo",    { undercurl = true, sp = c.blue })
hi("DiagnosticUnderlineHint",    { undercurl = true, sp = c.cyan })
hi("DiagnosticVirtualTextError", { fg = c.red,    bg = "#3d2330" })
hi("DiagnosticVirtualTextWarn",  { fg = c.yellow, bg = "#3d3a2a" })
hi("DiagnosticVirtualTextInfo",  { fg = c.blue,   bg = "#2a3040" })
hi("DiagnosticVirtualTextHint",  { fg = c.cyan,   bg = "#2a3840" })

-- Inlay Hints
hi("LspInlayHint", { fg = "#9d8faa", bg = "#3a3045", italic = true })

-- Git / Diff
hi("DiffAdd",     { fg = c.green,   bg = "#1e3a2a" })
hi("DiffChange",  { fg = c.yellow,  bg = "#3a3020" })
hi("DiffDelete",  { fg = c.red,     bg = "#3a1e20" })
hi("DiffText",    { fg = c.yellow,  bg = "#4a4020", bold = true })
hi("GitSignsAdd",     { fg = c.green })
hi("GitSignsChange",  { fg = c.yellow })
hi("GitSignsDelete",  { fg = c.red })

-- Treesitter
hi("@variable",               { fg = c.fg })
hi("@variable.builtin",       { fg = c.magenta, italic = true })
hi("@variable.parameter",     { fg = c.fg_dim })
hi("@variable.member",        { fg = c.fg })
hi("@constant",               { fg = c.yellow })
hi("@constant.builtin",       { fg = c.yellow, bold = true })
hi("@string",                 { fg = c.green })
hi("@string.escape",          { fg = c.cyan })
hi("@string.regexp",          { fg = c.cyan })
hi("@number",                 { fg = c.orange })
hi("@boolean",                { fg = c.magenta })
hi("@function",               { fg = c.cyan })
hi("@function.builtin",       { fg = c.cyan, italic = true })
hi("@function.call",          { fg = c.cyan })
hi("@function.method",        { fg = c.cyan })
hi("@function.method.call",   { fg = c.cyan })
hi("@constructor",            { fg = c.yellow })
hi("@keyword",                { fg = c.magenta, italic = true })
hi("@keyword.import",         { fg = c.blue })
hi("@keyword.operator",       { fg = c.cyan })
hi("@keyword.return",         { fg = c.magenta })
hi("@operator",               { fg = c.cyan })
hi("@punctuation.delimiter",  { fg = c.fg_dim })
hi("@punctuation.bracket",    { fg = c.fg_dim })
hi("@type",                   { fg = c.yellow })
hi("@type.builtin",           { fg = c.yellow, italic = true })
hi("@tag",                    { fg = c.magenta })
hi("@tag.attribute",          { fg = c.yellow })
hi("@tag.delimiter",          { fg = c.fg_dim })
hi("@comment",                { fg = c.comment, italic = true })
hi("@markup.heading",         { fg = c.cyan, bold = true })
hi("@markup.link",            { fg = c.blue, underline = true })
hi("@markup.link.label",      { fg = c.cyan })
hi("@markup.raw",             { fg = c.green })
hi("@markup.italic",          { italic = true })
hi("@markup.strong",          { bold = true })
